working_directory_and_steps_defaults: &working_directory_and_steps_defaults
  working_directory: ~/repo
  steps:
    - checkout
    - restore_cache:
        keys:
          - v1-dependencies-{{ .Branch }}-{{ .Revision }}
          - v1-dependencies-{{ .Branch }}
    - run:
        name: install dependencies
        command: |
          bundle install --jobs=4 --retry=3 --path vendor/bundle
    - save_cache:
        paths:
          - ./vendor/bundle
        key: v1-dependencies-{{ .Branch }}-{{ .Revision }}
    - run: bundle exec appraisal install
    # Fixes the following error: Could not find date-3.3.3 in any of the sources
    - run: BUNDLE_GEMFILE=/home/circleci/repo/gemfiles/rails_5_0.gemfile bundle --full-index
    - run: bundle exec appraisal rails-5-0 'cd spec/dummy/ && rails db:environment:set RAILS_ENV=test'
    - run: bundle exec appraisal rails-5-2 'cd spec/dummy/ && rails db:environment:set RAILS_ENV=test'
    - run: bundle exec appraisal 'cd spec/dummy/ && rake db:schema:load'
    - run: mkdir /tmp/test-results
    - run:
        name: run rails 5.0 tests
        command: |
          bundle exec appraisal rails-5-0 rspec -r rspec_junit_formatter --format progress --format RspecJunitFormatter
    - run:
        name: run rails 5.2 tests
        command: |
          bundle exec appraisal rails-5-2 rspec -r rspec_junit_formatter --format progress --format RspecJunitFormatter
    - store_test_results:
        path: /tmp/test-results
    - store_artifacts:
        path: /tmp/test-results
        destination: test-results

postgres_defaults: &postgres_defaults
  environment:
    POSTGRES_HOST: localhost
    POSTGRES_USER: filter_builder
    POSTGRES_DB: filter_builder_test
    POSTGRES_PASSWORD: filter_builder

version: 2
jobs:
  ruby_2.5.5_build_and_test:
    docker:
      - image: circleci/ruby:2.5.5
        environment:
          RAILS_ENV: test
      - image: circleci/postgres:9.6
        <<: *postgres_defaults
    <<: *working_directory_and_steps_defaults

  ruby_2.7.4_build_and_test:
    docker:
      - image: circleci/ruby:2.7.4
        environment:
          RAILS_ENV: test
      - image: circleci/postgres:9.6
        <<: *postgres_defaults
    <<: *working_directory_and_steps_defaults

workflows:
  version: 2
  build_and_test:
    jobs:
      - ruby_2.7.4_build_and_test
      - ruby_2.5.5_build_and_test
